apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eck-ui

resources:
  - 00-namespace.yaml
  - 01-rbac.yaml
  - 02-backend-deployment.yaml
  - 03-backend-service.yaml
  - 04-frontend-deployment.yaml
  - 05-frontend-service.yaml
  - 06-ingress.yaml

commonLabels:
  app: eck-ui
  managed-by: kustomize

images:
  - name: eck-ui-backend
    newName: eck-ui-backend
    newTag: latest
  - name: eck-ui-frontend
    newName: eck-ui-frontend
    newTag: latest
